### PR TITLE
Intro video before game starts

### LINKED ISSUE #16: Intro for the game
For the game to look better presented, it must have an intro before the game begins. This should be a short video that presents the logo of the game, the creators and, if it exists, the web page that contains more details of the game.

Consider tools like this: https://intromaker.com/

### PR DESCRIPTION
**Pull request by clausia**
For the game to look better presented, it must have an intro before the game begins. This should be a short video that presents the logo of the game, the creators and, if it exists, the web page that contains more details of the game.

Consider tools like this: https://intromaker.com/

---------------------

This PR also includes a personalized icon to show in the game's window.

The names of the developers or a website are not included, because it was requested as part of the hackathon that the deliverable does not include data that can identify us, so that in this way the jury could be as impartial as possible

Closes #16 

Needs to install:
`pip install opencv-python`

### CODE REVIEW

**Review by Isamade — COMMENTED** [review]
I got the error 'No module named cv2', is that a library I need to download?

**Comment by clausia** [comment]
> I got the error 'No module named cv2', is that a library I need to download?

@Isamade 
Sorry, I forgot to mention, yes, in order to show the video it is needed to install:
`pip install opencv-python`

**Review by iguanajazz — APPROVED** [review]
looks great!

**Comment by Isamade** [comment]
🤯 It's perfect!!!

**Pull request merged**
