### PR TITLE
Counter for lines

### LINKED ISSUE #2: Counter for created lines
For now, only the score that increases when creating lines is shown, but it does not indicate how many lines have been created, and it is useful to know this information, so a line counter must be added, independent of the score.

### PR DESCRIPTION
**Pull request by Isamade**
Added counter for lines. Changes might have to be made to show more than one piece to come

Closes #2

### CODE REVIEW

**Comment by clausia** [comment]
@Isamade Mention the issue number please

**Comment by Isamade** [comment]
@clausia Issue #2 (sorry I added it in the description of the commit)

**Comment by clausia** [comment]
> @clausia Issue #2 (sorry I added it in the description of the commit)

@Isamade You're right, mention an issue in a commit also works.
But has to say "close #n" or similar (see options [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)) (both in a _commit message_ **or** in the _PR description_) 😺

**Review by clausia — APPROVED** [review]
I like this changes 👍

**Comment by Isamade** [comment]
Okay, I'll remember that. Thanks!

**Comment by iguanajazz** [comment]
@Isamade you need to add "Closes # \<Num of issue\>" on PR description so the PR is linked to the issue

**Review by iguanajazz — APPROVED** [review]
looks good 👍

**Comment by Isamade** [comment]
Ooh now I properly understand. I thought the message for the reviewers. Claudia has done it. Thanks

**Pull request merged**
